package ie.gaeilge.learning.core.designsystem

object AppStrings {
    const val appName = "Gaeilge"
    const val appTagline = "Your Irish, one day at a time."
    const val continueLearning = "Continue learning"
    const val startLesson = "Start lesson"
    const val viewLessons = "View all lessons"
    const val todaysProgress = "Today's progress"
    const val lessonsComplete = "lessons complete"
    const val minutes = "min"
    const val welcome = "Fáilte"
    const val lessons = "Lessons"
    const val quiz = "Quiz"
    const val playGame = "Play picture game"
    const val picturePrompt = "Tap the picture for"
    const val correct = "Maith thú!"
    const val tryAgain = "Nearly! Try another picture."
    const val next = "Next"
    const val finish = "Finish"
    const val gameComplete = "Cluiche críochnaithe!"
    const val score = "score"
    const val xp = "XP"
    const val streak = "streak"
    const val pointsEarned = "points earned"
    const val playAgain = "Play again"
}
